import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./../components/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <>
          <div className="bg-[radial-gradient(circle_500px_at_50%_200px,#C9EBFF,transparent)]">
          <Navbar />
          {children}
          </div>
          </>
        </body>
      </html>
    );
  }